### ISSUE TITLE
SciPy fails sanity check, but no checks are defined in block or config

### ISSUE THREAD

**Issue by ajdecon** [hpcugent/easybuild-easyblocks#241] opened 2013-08-12 06:11 UTC
Building SciPy with the scipy-0.11.0-goalf-1.1.0-no-OFED-Python-2.7.3.eb easyconfig, I observe a failure in the sanity check step. This happens even though, as far as I can tell, no sanity checks are defined in either the easyblock or easyconfig for SciPy.

The system is a newly installed Debian Wheezy virtual machine installed on my Macbook Air. EasyBuild is version 1.6.0.

```
ajdecon@debian:~/.local/easybuild/easyconfigs/s/scipy$ eb scipy-0.11.0-goolf-1.4.10-Python-2.7.3.eb== temporary log file in case of crash /tmp/easybuild-j2235m.log
== resolving dependencies ...
== processing EasyBuild easyconfig /home/ajdecon/.local/easybuild/easyconfigs/s/scipy/scipy-0.11.0-goolf-1.4.10-Python-2.7.3.eb
== building and installing scipy-0.11.0-goolf-1.4.10-Python-2.7.3...
== fetching files...
== creating build dir, resetting environment...
== unpacking...
== patching...
== preparing...
== configuring...
== building...
== testing...
== installing...
== taking care of extensions...
== packaging...
== postprocessing...
== sanity checking...
ERROR: EasyBuild encountered an exception (at easybuild/main.py:827 in build_and_install_software): autoBuild Failed (last 300 chars): EasyBuild crashed with an error (at easybuild/framework/extensioneasyblock.py:125 in sanity_check_step): Sanity check for scipy failed!
ajdecon@debian:~/.local/easybuild/easyconfigs/s/scipy$
```

**Comment by boegel** [comment] 2015-08-23 15:28
@ajdecon: did you ever get to the bottom of this, i.e. why the scipy build failed?

I'd like to get this closed, afaict the sanity check did what it was intended to do.

**Comment by boegel** [comment] 2016-01-23 13:44
not a bug, but a feature, closing (do let me know if you disagree @ajdecon!)

**Closed by boegel** 2016-01-23 13:44 UTC
Labels: bug, priority (1) low, software-specific

**Comment by ajdecon** [comment] 2016-01-23 20:34
I agree that this is a feature, no problem with closing it. Thanks!
