### ISSUE TITLE
pythonpackage working in easybuild 1.16.2 but not working in easybuild 2.0.0

### ISSUE THREAD

**Issue by pescobar** [hpcugent/easybuild-easyblocks#575] opened 2015-03-09 09:57 UTC
This is the build log using EasyBuild 2.0.0 which fails in the install_step:
https://gist.github.com/anonymous/7718e36e17182e295cbd

An this is the build log for the same easyconfig using EasyBuild 1.16.2 which works fine:
https://gist.github.com/173c12d30680d5f72b51

**Comment by boegel** [comment] 2015-03-09 09:58
@pescobar: can you share the output of `find /soft/apps/EasyBuild/2.0.0/lib/python2.7/site-packages -type d` with us?

I have no idea why this is failing like that...

**Comment by pescobar** [comment] 2015-03-09 09:58
Here you have

https://gist.github.com/41337750c26c5e674de2

**Comment by boegel** [comment] 2015-03-11 08:46
easyconfig used at https://gist.github.com/anonymous/a01485310527ed718639, Python easyconfig required for it at https://gist.github.com/e6b19981efef577b1d63

**Comment by boegel** [comment] 2015-03-17 09:30
@pescobar: I just checked, I can't reproduce this problem on SL6, the installation of StarCluster is working fine for me...

This seems to suggest it's related to the version of setuptools being used: https://github.com/gotcha/ipdb/issues/60 .

That may explain it, because I see that `eb` is using your system setuptools, rather than the one provided in the Python module you're using:

```
/usr/lib/python2.7/dist-packages/setuptools/command/install.py
```

Can you figure out which version of setuptools that is? We'll need to figure out why that one 'wins' over the one provided by the Python module.

Can you also share the contents of `$EBROOTPYTHON/lib/python2.7/site-packages/easy-install.pth` ?

**Comment by boegel** [comment] 2015-12-31 15:14
This looks related to https://github.com/hpcugent/easybuild-framework/issues/1409?

**Comment by boegel** [comment] 2016-01-23 13:36
Most likely fixed by https://github.com/hpcugent/easybuild-framework/pull/1569 and #813.

@pescobar: please check if you're still seeing this problem with EasyBuild v2.6.0 (will be available soon)

I'm fairly certain it will be resolved, so I'll go ahead and close this until further notice.

**Closed by boegel** 2016-01-23 13:36 UTC
